# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urun_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 639)
        MainWindow.setStyleSheet("/* Genel stil kuralları */\n"
"* {\n"
"  background-color: #333333; /* Mavi arka plan */\n"
"  color: #FFFFFF; /* Beyaz yazı */\n"
"}\n"
"\n"
"/* Sekmeler için stil kuralları */\n"
"QTabBar::tab {\n"
"  background-color: #333333; /* Sekmelerin arka plan rengi */\n"
"  color: #ffffff; /* Beyaz yazı rengi */\n"
"  margin-left: 5px; /* Solda 5px boşluk bırak */\n"
"  margin-right: 5px; /* Sağda 5px boşluk bırak */\n"
"  border-right: 1px solid #E0E0E0; /* Kalın separator */\n"
"  border-image: linear-gradient(to right, #E0E0E0 0%, #F5F5F5 50%, #E0E0E0 100%); /* Sekmelerin arasına gölge ekleme */\n"
"}\n"
"\n"
"/* Fare üzerine geldiğinde sekmelerin rengi değişir */\n"
"QTabBar::tab:hover {\n"
"  background-color: #0651ff; /* Fare üzerine gelince arka plan rengi */\n"
"}\n"
"\n"
"/* Seçili sekmenin rengi değişir */\n"
"QTabBar::tab:selected {\n"
"  background-color:#2980b9; /* Seçili sekmenin arka plan rengi */\n"
"}\n"
"\n"
"/* Açılır menü stil kuralları */\n"
"QComboBox, QComboBox::drop-down {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  background-color: #ffffff; /* Açılır menünün arka plan rengi */\n"
"}\n"
"\n"
"/* Seçili öğenin arka plan rengi */\n"
"QComboBox::item:selected {\n"
"  background-color: #eee;\n"
"}\n"
"\n"
"/* Açılır menü ok simgesi */\n"
"QComboBox::down-arrow {\n"
"  image: url(:/siyah/asagi.png); /* Ok simgesi */\n"
"  width: 16px; /* Ok resminin genişliği */\n"
"  height: 16px; /* Ok resminin yüksekliği */\n"
"}\n"
"\n"
"/* Açılır menü öğelerinin hover ve pressed efektleri */\n"
"QComboBox::item:hover {\n"
"  background-color: #f9f9f9;\n"
"}\n"
"\n"
"QComboBox::item:pressed {\n"
"  background-color: #ddd;\n"
"}\n"
"\n"
"/* Giriş kutuları ve açılır menülerin genel stil kuralları */\n"
" QComboBox {\n"
"  background-color: #ffffff; /* Arka plan rengi beyaz */\n"
"  color: #333333; /* Yazı rengi */\n"
"}\n"
"QLineEdit {\n"
"  background-color: #ffffff; /* Başlangıçta arka plan rengi beyaz */\n"
"}\n"
"\n"
"QLineEdit:!enabled {\n"
"  background-color: #ffff00; /* İçeriği dolu olan QLineEdit\'in arka plan rengi sarı */\n"
"}\n"
"\n"
"/* Butonların stil kuralları */\n"
"QPushButton, QToolButton {\n"
"  background-color: #333333; /* Arka plan rengi kırmızı */\n"
"  color: #ffffff; /* Yazı rengi beyaz */\n"
"}\n"
"\n"
"/* Buton hover efekti */\n"
"QPushButton:hover, QToolButton:hover {\n"
"  background-color: #c0392b; /* Hover rengi */\n"
"}\n"
"\n"
"/* Butonların stil kuralları */\n"
"QPushButton, QToolButton {\n"
"  background-color:  #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi beyaz */\n"
"  border: 1px solid #b3ff26; /* Kenarlık */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  padding: 8px 16px; /* Buton içeriği için dolgular */\n"
"}\n"
"\n"
"/* Buton hover efekti */\n"
"QPushButton:hover, QToolButton:hover {\n"
"  background-color: #2980b9; /* Hover rengi */\n"
"  border-color: #2980b9; /* Kenarlık rengi */\n"
"}\n"
"\n"
"/* Buton basılma efekti */\n"
"QPushButton:pressed, QToolButton:pressed {\n"
"  background-color: #1f618d; /* Basılma rengi */\n"
"  border-color: #1f618d; /* Kenarlık rengi */\n"
"}\n"
"\n"
"/* Radyo düğmelerinin stil kuralları */\n"
"QRadioButton {\n"
"  color: #white; /* Yazı rengi */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"  width: 16px; /* Gösterge genişliği */\n"
"  height: 16px; /* Gösterge yüksekliği */\n"
"  border: 2px solid #3498db; /* Kenarlık rengi */\n"
"  border-radius: 8px; /* Gösterge köşeleri yuvarlatma */\n"
"  background-color: #ffffff; /* Arka plan rengi */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  background-color: #3498db; /* Seçili arka plan rengi */\n"
"  border-color: #3498db; /* Seçili kenarlık rengi */\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"  border-color: #2980b9; /* Hover kenarlık rengi */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover {\n"
"  background-color: #2980b9; /* Seçili hover arka plan rengi */\n"
"  border-color: #2980b9; /* Seçili hover kenarlık rengi */\n"
"}\n"
"\n"
"/* QLineEdit stil kuralları */\n"
"QLineEdit,QTextEdit {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  /*padding: 6px; /* İçerik dolgusu */\n"
"  background-color: #ffffff; /* Arka plan rengi */\n"
"  color: #333333; /* Yazı rengi */\n"
"}\n"
"\n"
"/* QLineEdit hover efekti */\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"  border-color: #3498db; /* Kenarlık rengi */\n"
"}\n"
"\n"
"/* QLineEdit odaklandığında */\n"
"QLineEdit:focus {\n"
"  border-color: #3498db; /* Kenarlık rengi */\n"
"}\n"
"QTextEdit:focus {\n"
"  border-color: #3498db; /* Kenarlık rengi */\n"
"}\n"
"\n"
"/* Etiketlerin (QLabel) stil kuralları */\n"
"QLabel {\n"
"  color: white; /* Yazı rengi */\n"
"text-align: center;\n"
"}\n"
"\n"
"/* Etiketlerin hover efekti */\n"
"QLabel:hover {\n"
"  color: yellow; /* Hover rengi */\n"
"}\n"
"\n"
"/* Tablo Widget stil kuralları */\n"
"QTableWidget {\n"
"  alternate-background-color: #f5f5f5; /* Alternatif satır arka plan rengi */\n"
"  background-color: #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi */\n"
"  selection-background-color: #3498db; /* Seçili arka plan rengi */\n"
"  selection-color: #ffffff; /* Seçili yazı rengi */\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  gridline-color: white;\n"
"  gridline-width: 1px; /* Satır ve sütun çizgilerinin kalınlığı */\n"
"}\n"
"\n"
"/* Tablo Widget satır hover efekti */\n"
"QTableWidget::item:hover {\n"
"  background-color: #f0f0f0; /* Satır üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"\n"
"/* Tablo Widget başlık stil kuralları */\n"
"QHeaderView::section {\n"
"  background-color: #333333; /* Başlık arka plan rengi */\n"
"  color: #ffffff; /* Başlık yazı rengi */\n"
"  padding: 4px; /* Başlık dolgusu */\n"
"  border: none; /* Başlık kenarlığı yok */\n"
"  font-weight: bold; /* Kalın yazı tipi */\n"
"  font-size: 11pt; /* 11 punto yazı boyutu */\n"
"}\n"
"\n"
"/* Tablo Widget hücre içeriği */\n"
"QTableWidget QTableWidget::item {\n"
"  font-family: Arial; /* Yazı tipi */\n"
"  font-size: 11pt; /* 11 punto yazı boyutu */\n"
"}\n"
"\n"
"/* Tablo Widget\'in içeriğini sığdırma */\n"
"QTableView {\n"
"  font-size: 11pt; /* Yazı boyutu */\n"
"  alternate-background-color: #f5f5f5; /* Alternatif satır arka plan rengi */\n"
"  background-color: #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi */\n"
"}\n"
"\n"
"/* Tablo Widget başlık hover efekti */\n"
"QHeaderView::section:hover {\n"
"  background-color: #2980b9; /* Başlık üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"\n"
"/* QGroupBox stil kuralları */\n"
"QGroupBox {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 6px; /* Kenarlık köşeleri yuvarlatma */\n"
"  padding: 6px; /* İçerik dolgusu */\n"
"  background-color: #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi */\n"
"}\n"
"\n"
"/* QGroupBox başlık stil kuralları */\n"
"QGroupBox::title {\n"
"  subcontrol-origin: margin; /* Başlık başlangıç noktası */\n"
"  subcontrol-position: top left; /* Başlık pozisyonu */\n"
"  left: 10px; /* Sol boşluk */\n"
"  padding: 0 6px; /* Başlık içeriği için dolgu */\n"
"  background-color: #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi */\n"
"}\n"
"\n"
"/* İç içe tablar için stil kuralları */\n"
"QTabWidget::pane {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  background-color: #ffffff; /* Arka plan rengi */\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"  alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  min-width: 8ex;\n"
"  padding: 4px;\n"
"  border: 1px solid grey; /*#ccc;*/ /* Kenarlık rengi ve kalınlığı */\n"
"  background-color: #f5f5f5; /* Arka plan rengi */\n"
"  color: #333333; /* Yazı rengi */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"  background-color: #333333; /* Seçili sekmenin arka plan rengi */\n"
"  color: #ffffff; /* Seçili sekmenin yazı rengi */\n"
"}\n"
"\n"
"/* Tablodaki satırlar ve sütunlar arası çizgilerin rengini beyaz ve ince yapma */\n"
"QTableWidget QTableView {\n"
"  gridline-color: white; /* Satır ve sütun çizgilerinin rengi */\n"
"  gridline-width: 1px; /* Satır ve sütun çizgilerinin kalınlığı */\n"
"}\n"
"\n"
"/* QLineEdit içeriğinde yazı varken arka plan rengini sarı yapma */\n"
"/*QLineEdit {\n"
"  background-color: #ffffff; /* Başlangıçta arka plan rengi beyaz }*/\n"
"\n"
"\n"
"/*QLineEdit:focus {\n"
"  background-color: #ffff00; /* İçeriğe odaklandığında arka plan rengi sarı }*/\n"
"\n"
"\n"
"/* QLineEdit içeriği doluyken arka plan rengini sarı yapma */\n"
"\n"
"/* Combobox stil kuralları */\n"
"QComboBox {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  background-color: #ffffff; /* Arka plan rengi */\n"
"}\n"
"\n"
"/* Combobox üzerine gelindiğinde */\n"
"QComboBox:hover {\n"
"  background-color: #ffff00; /* Sarı arka plan rengi */\n"
"}\n"
"\n"
"/* LineEdit stil kuralları */\n"
"QLineEdit {\n"
"  border: 1px solid #ccc; /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 4px; /* Kenarlık köşeleri yuvarlatma */\n"
"  background-color: #ffffff; /* Arka plan rengi */\n"
"}\n"
"\n"
"/* LineEdit üzerine gelindiğinde */\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"  background-color: #ffff00; /* Sarı arka plan rengi */\n"
"}\n"
"\n"
"/* GroupBox stil kuralları */\n"
"QGroupBox {\n"
"  border: 2px solid grey;/*#ccc;*/ /* Kenarlık rengi ve kalınlığı */\n"
"  border-radius: 6px; /* Kenarlık köşeleri yuvarlatma */\n"
"  padding: 6px; /* İçerik dolgusu */\n"
"  background-color: #333333; /* Arka plan rengi */\n"
"  color: #ffffff; /* Yazı rengi */\n"
"}\n"
"\n"
"/* GroupBox üzerine gelindiğinde */\n"
"QGroupBox:hover {\n"
"  background-color: #ffff00; /* Sarı arka plan rengi */\n"
"color:#ffffff /* Yazı rengi */\n"
"}\n"
"\n"
"/* CheckButton ve RadioButton stil kuralları */\n"
"QCheckBox, QRadioButton {\n"
"  color: #ffffff; /* Yazı rengi */\n"
"}\n"
"\n"
"/* CheckButton ve RadioButton üzerine gelindiğinde */\n"
"QCheckBox:hover, QRadioButton:hover {\n"
"  background-color: #ffff00; /* Sarı arka plan rengi */\n"
"  color: black; /* Yazı rengi */\n"
"  border-radius: 3px; /* Kenarlık köşeleri yuvarlatma */\n"
"  /*padding: 1px; /* İçerik dolgusu */\n"
"}\n"
"\n"
"/*--------------------------------------------------------------------*/\n"
"\n"
"/* StackedWidget ileri ve geri butonlarının stil kuralları */\n"
"QStackedWidget > QAbstractButton {\n"
"  background-color: #333333; /* Arka plan rengi ile aynı renk */\n"
"  border: none; /* Kenarlık yok */\n"
"  width: 0; /* Genişlik sıfır */\n"
"  height: 0; /* Yükseklik sıfır */\n"
"}\n"
"\n"
"/* İleri ve geri butonlarının üzerine gelindiğinde */\n"
"QStackedWidget > QAbstractButton:hover {\n"
"  background-color: #333333; /* Arka plan rengi ile aynı renk */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.widget_8)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lne_urunkodu = QtWidgets.QLineEdit(self.widget)
        self.lne_urunkodu.setText("")
        self.lne_urunkodu.setObjectName("lne_urunkodu")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lne_urunkodu)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lne_urunadi = QtWidgets.QLineEdit(self.widget)
        self.lne_urunadi.setObjectName("lne_urunadi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lne_urunadi)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lne_birimfiyat = QtWidgets.QLineEdit(self.widget)
        self.lne_birimfiyat.setObjectName("lne_birimfiyat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lne_birimfiyat)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lne_stokmiktari = QtWidgets.QLineEdit(self.widget)
        self.lne_stokmiktari.setObjectName("lne_stokmiktari")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lne_stokmiktari)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_8)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.txt_urunaciklamas = QtWidgets.QTextEdit(self.widget_2)
        self.txt_urunaciklamas.setObjectName("txt_urunaciklamas")
        self.verticalLayout.addWidget(self.txt_urunaciklamas)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_8)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.cmb_kategori = QtWidgets.QComboBox(self.widget_3)
        self.cmb_kategori.setObjectName("cmb_kategori")
        self.cmb_kategori.addItem("")
        self.cmb_kategori.addItem("")
        self.cmb_kategori.addItem("")
        self.gridLayout.addWidget(self.cmb_kategori, 1, 1, 1, 1)
        self.cmb_marka = QtWidgets.QComboBox(self.widget_3)
        self.cmb_marka.setObjectName("cmb_marka")
        self.cmb_marka.addItem("")
        self.cmb_marka.addItem("")
        self.cmb_marka.addItem("")
        self.cmb_marka.addItem("")
        self.gridLayout.addWidget(self.cmb_marka, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.gridLayout_2.addWidget(self.widget_8, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.cmb_kategoriyegorelistele = QtWidgets.QComboBox(self.widget_5)
        self.cmb_kategoriyegorelistele.setObjectName("cmb_kategoriyegorelistele")
        self.cmb_kategoriyegorelistele.addItem("")
        self.cmb_kategoriyegorelistele.addItem("")
        self.cmb_kategoriyegorelistele.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_kategoriyegorelistele)
        self.btn_kategoriyegore_listele = QtWidgets.QPushButton(self.widget_5)
        self.btn_kategoriyegore_listele.setObjectName("btn_kategoriyegore_listele")
        self.horizontalLayout_2.addWidget(self.btn_kategoriyegore_listele)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.tablowidget = QtWidgets.QTableWidget(self.widget_6)
        self.tablowidget.setRowCount(30)
        self.tablowidget.setColumnCount(7)
        self.tablowidget.setObjectName("tablowidget")
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablowidget.setVerticalHeaderItem(18, item)
        self.tablowidget.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tablowidget)
        self.gridLayout_2.addWidget(self.widget_6, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_urunEkle = QtWidgets.QPushButton(self.widget_4)
        self.btn_urunEkle.setObjectName("btn_urunEkle")
        self.horizontalLayout.addWidget(self.btn_urunEkle)
        self.btn_urunsil = QtWidgets.QPushButton(self.widget_4)
        self.btn_urunsil.setObjectName("btn_urunsil")
        self.horizontalLayout.addWidget(self.btn_urunsil)
        self.btn_urunguncelle = QtWidgets.QPushButton(self.widget_4)
        self.btn_urunguncelle.setObjectName("btn_urunguncelle")
        self.horizontalLayout.addWidget(self.btn_urunguncelle)
        self.btn_urun_listele = QtWidgets.QPushButton(self.widget_4)
        self.btn_urun_listele.setObjectName("btn_urun_listele")
        self.horizontalLayout.addWidget(self.btn_urun_listele)
        self.gridLayout_2.addWidget(self.widget_4, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmb_kategori.setCurrentIndex(-1)
        self.cmb_marka.setCurrentIndex(-1)
        self.cmb_kategoriyegorelistele.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ürün Kodu"))
        self.label_2.setText(_translate("MainWindow", "Ürün Adı"))
        self.label_3.setText(_translate("MainWindow", "Birim Fiyat"))
        self.label_4.setText(_translate("MainWindow", "Stok Miktarı"))
        self.label_5.setText(_translate("MainWindow", "Ürün Açıklaması"))
        self.label_8.setText(_translate("MainWindow", "Ürün Kategorisi"))
        self.cmb_kategori.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmb_kategori.setItemText(1, _translate("MainWindow", "Bilgisayar"))
        self.cmb_kategori.setItemText(2, _translate("MainWindow", "Beyaz Eşya"))
        self.cmb_marka.setItemText(0, _translate("MainWindow", "Acer"))
        self.cmb_marka.setItemText(1, _translate("MainWindow", "Samsung"))
        self.cmb_marka.setItemText(2, _translate("MainWindow", "Apple"))
        self.cmb_marka.setItemText(3, _translate("MainWindow", "Oppo"))
        self.label_7.setText(_translate("MainWindow", "Ürün Markası"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Kategoriye Göre Listele</p></body></html>"))
        self.cmb_kategoriyegorelistele.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmb_kategoriyegorelistele.setItemText(1, _translate("MainWindow", "Bilgisayar"))
        self.cmb_kategoriyegorelistele.setItemText(2, _translate("MainWindow", "Beyaz Eşya"))
        self.btn_kategoriyegore_listele.setText(_translate("MainWindow", "Kategoriye Göre Listele"))
        item = self.tablowidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tablowidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tablowidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tablowidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tablowidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tablowidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tablowidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tablowidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tablowidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tablowidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tablowidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tablowidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tablowidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tablowidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tablowidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tablowidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tablowidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tablowidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tablowidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "20"))
        self.btn_urunEkle.setText(_translate("MainWindow", "Ürün Ekle"))
        self.btn_urunsil.setText(_translate("MainWindow", "Ürün Sil"))
        self.btn_urunguncelle.setText(_translate("MainWindow", "Ürün Güncelleme"))
        self.btn_urun_listele.setText(_translate("MainWindow", "Ürün Listeleme"))
